### ISSUE TITLE
Failure message with "state: up" option when creating bonded interface.

### ISSUE THREAD

**Issue by tabowling** [linux-system-roles/network#1]
Example playbook:

```
---
- hosts: rhel7-latest
  vars_files:
  become: yes
  become_method: sudo
  become_user: root
  vars:
  roles:
    - role: linux-system-roles.network   # Configure Networking
      network:
        provider: nm    # or initscripts
        connections:

          - name: DBnic
            state: up
            type: ethernet
            interface_name: eth1
            autoconnect: yes
            ip:
              dhcp4: yes
              auto6: no

          - name: WebBond
            type: bond
            autoconnect: yes
            ip:
              dhcp4: yes
              auto6: no

          - name: WebBond-linkA
            type: ethernet
            interface_name: eth2
            master: WebBond
            slave_type: bond

          - name: WebBond-linkB
            type: ethernet
            interface_name: eth3
            master: WebBond
            slave_type: bond

```

Results:

1. Single, regular connection DBnic is created and brought up with the "state: up" option, though it does produce an unexpected 

` [WARNING]: <warn>  #0, state:up, "DBnic": wait for activation is not yet implemented
`
2. WebBond interface creates error message when created and brought up with the "state: up" option, though it does complete with active state.

```
TASK [linux-system-roles.network : Configure networking connection profiles] *****************************************************************
task path: /etc/ansible/roles/linux-system-roles.network/tasks/main.yml:20
 [WARNING]: <info>  #0, state:up, "DBnic": add connection DBnic, 1e2ea869-fbe0-49c1-aa7a-65e44bace54a

 [WARNING]: <warn>  #0, state:up, "DBnic": wait for activation is not yet implemented

 [WARNING]: <info>  #0, state:up, "DBnic": up connection DBnic, 1e2ea869-fbe0-49c1-aa7a-65e44bace54a

 [WARNING]: <info>  #1, state:present, "WebBond": add connection WebBond, 56592fb3-3feb-47ae-b908-bd8079758d50

 [WARNING]: <info>  #2, state:present, "WebBond-linkA": add connection WebBond-linkA, 31cdf4b5-7be3-4ec0-b600-a86412328441

 [WARNING]: <info>  #3, state:present, "WebBond-linkB": add connection WebBond-linkB, cefdeb90-22d5-4991-a6e4-cbac42b45ebd

 [WARNING]: <info>  #4, state:up, "MyApp-Team": add connection MyApp-Team, be90452c-7c56-4df0-bf59-d365685835fd

 [WARNING]: <warn>  #4, state:up, "MyApp-Team": wait for activation is not yet implemented

 [WARNING]: <info>  #4, state:up, "MyApp-Team": up connection MyApp-Team, be90452c-7c56-4df0-bf59-d365685835fd

 [WARNING]: <error> #4, state:up, "MyApp-Team": up connection failed: failure to activate connection: nm-client-error-quark: Active
connection removed before it was initialized (2)

fatal: [rhel7-latest]: FAILED! => {"changed": false, "failed": true, "msg": "error: up connection failed: failure to activate connection: nm-client-error-quark: Active connection removed before it was initialized (2)"}
	to retry, use: --limit @/home/tbowling/src/virt-demo/ansible/example-linux-system-roles.network.retry

PLAY RECAP ***********************************************************************************************************************************
rhel7-latest               : ok=4    changed=0    unreachable=0    failed=1   

```

Expected results:
It seems that when creating an interface, the default behavior is to also activate it.  However, the expecation is that if "state: up" is specified, there should be no errors or warnings.

**Comment by thom311** [comment]
> [WARNING]: <warn> #0, state:up, "DBnic": wait for activation is not yet implemented

this warning is harmless. The feature is implemented by https://github.com/linux-system-roles/network/pull/4 . The pull request addresses this.

> [WARNING]: <error> #4, state:up, "MyApp-Team": up connection failed: failure to activate connection: nm-client-error-quark: Active
connection removed before it was initialized (2)

This failure seems to come from NetworkManager. It's unclear why it happened, it's probably a bug in libnm or NetworkManager. I saw it occasionally in rhel-7.3 (NM 1.4.0), but didn't see it against rhel-7.4 (1.8.0). @tabowling , what was the NM version you were using?

**Comment by tabowling** [comment]
@thom311  I'm testing with Fedora 25 and getting the message consistently.
NetworkManager-1.4.4-5.fc25.x86_64
NetworkManager-libnm-1.4.4-5.fc25.x86_64

**Comment by tabowling** [comment]
@thom311   Yes, you are correct.  I was not using that commit.  Warning messages are gone now.

**Comment by thom311** [comment]
@tabowling , when you said 

>  I'm testing with Fedora 25 and getting the message consistently.

were you talking about the warning? Yes, that will be fixed, it's no issue.


The other failure "Active connection removed before it was initialized" is more concerning. Do you encounter that regularly, and more importantly: do you encounter that on rhel-7.4 or Fedora 26? -- it should be fixed there.

If you do, it warrants for further investigation. Otherwise, I would claim the bug is fixed in NetworkManager.

Thanks!
