### ISSUE TITLE
RFE: Allow user-defined attributes in network_connections structure

### ISSUE THREAD

**Issue by forsetti** [linux-system-roles/network#15]
The network_connections struct is a good general data model for network connections, and could be used by more than just the linux-system-roles.network role.  The value of this struct would be greatly increased if other attributes could be added, beyond what is useful by this role.  However, adding user-defined attributes to network_connections that are not recognized by this role generates a failure.

Please consider tolerating user-defined attributes within the network_connections struct, without generating a failure in the linux-system-roles.network role

Example below.  Note addition of non-standard "libvirt_dev", for use by another role in the same playbook.  I use this to create a VM by generating a domain.xml with matching network devices which I supply to the libvirt module.  Then when the VM is running, I could apply the linux-system-roles.network role to the guest.  However, this does not work, because linux-system-roles.network generates a failure because of my addition "libvirt_dev" attribute.

host_vars/foo.example.com/main.yml:
---
network_connections:
- name: "eth0"
  type: "ethernet"
  mac: "12:34:56:78:9a:bc"
  ip:
    dhcp4: yes
  libvirt_dev: eno1.2
---

Playbook execution:
---
TASK [linux-system-roles.network : Configure networking connection profiles] ***************************************************************************************************
fatal: [foo.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "configuration error: connections[0]: invalid key \"libvirt_dev\""}
---

If it is necessary to maintain a level of restrictiveness to the schema, I'd request either creating a new "network_user_attrs" data element which contains a list of user-defined attributes to be allowed within the struct, or use of a prefix such as "user_" for user-defined attributes.

**Comment by thom311** [comment]
Yes, that would be possible to do... not sure though, if it's the right thing to do... :)

**Comment by forsetti** [comment]
Agreed - unsure if it's the "right" thing.  Having a unified data model for
network info is a (very) nice-to-have; but if you see it interfering with
goals of this role, then I'd close this WONTFIX.

**Comment by thom311** [comment]
I think the patch itself is trivial. Basically, it reserves the name "user_attrs" for external use. Only minor downside is the added code, and that this particular name is now taken.

I am just not sure anybody would use it, or that it looks nice for the user to make use of this...

Would this patch solve your use-case nicely?

**Comment by forsetti** [comment]
Likely, yes - with your user_attrs approach, using my initial example, how
would the network_connections dict look to support the libbvirt_dev
attribute? And, for playing out this example, lets add another foo_bar
attribute to the "ip:" dict too.

On Sep 25, 2017 2:59 PM, "Thomas Haller" <notifications@github.com> wrote:

I think the patch itself is trivial. Basically, it reserves the name
"user_attrs" for external use. Only minor downside is the added code, and
that this particular name is now taken.

I am just not sure anybody would use it, or that it looks nice for the user
to make use of this...

Would this patch solve your use-case nicely?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/linux-system-roles/network/issues/15#issuecomment-331979397>,
or mute the thread

**Comment by thom311** [comment]
Well, with the patch in the current form, you could not extend the "ip" dictionary. But that wouldn't matter, because "ip" is a only a dictionary, not a list. So instead of

```
  - name: "eth0"
    ...
    ip:
       foo_bar: value
```

you'd have to do: 

```
network_connections:
  - name: "eth0"
    type: "ethernet"
    mac: "12:34:56:78:9a:bc"
    ip:
        dhcp4: yes
    user_attrs:
        libvirt_dev: eno1.2
        ip:
            foo_bar: value
```

or

```
    user_attrs:
        libvirt_dev: eno1.2
        ip_foo_bar: value
```

**Comment by forsetti** [comment]
Hrmmm, ok, I see what you are suggesting now.

Yes, that would /suffice/, but I don't think there is value in implementing
this way.  There really is no functional difference versus just moving the
entire user_attrs dicts outside of network_connection and call it
other_network_attrs.

What started this thinking for me was the recognition that the entire data
struct you've defined for network_connections is a really good /general
purpose model/.  Being able to decorate the model with additional
attributes would be valuable by keeping a unified set of network config.
But this requires being able to extend the model as a whole, not just
adding a new top-level dict to each connection.

I could see doing this with a prefix, like:

network_connections:
  - name: "eth0"
    type: "ethernet"
    mac: "12:34:56:78:9a:bc"
    ip:
        dhcp4: yes

        user_foo_bar: value

    user_libvirt_dev: eno1.2


Or, by creating a top-level attr called user_attrs which contains a list of
attrs to be allowed elsewhere within the model (i.e., ignore these
attributes for validation checks).  Note the hope would be that after
deployers use these for a period, they would propose moving these attrs
directly into your network model without needing the user_attrs declaration.

network_connections:
  user_attrs:
  - "libvirt_dev"
  - "ip.foo_bar"
- name: eth0
  libvirt_dev: eno1.2
  ...
  ip:
    ...
    foo_bar: value

Sadly, I believe I'm thinking about this the same way I'd extend a XML
document with a well-defined schema by using my own additional namespaces.

With this additional thought, and to avoid overcomplicating this more than
necessary, here's my thinking:
- If you have interest in maintaining a well-defined network model /in
addition to/ this specific Ansible role, then there may be value in this.
But I recognize I'm asking for more work, and I haven't see anyone except
me ask for this.
- If the effort is focused on implementation of the role, and the
time/effort vs value balance doesn't make sense to also shoulder the burden
of the model for just my needs, then we should probably WONTFIX this, at
least until others chime in with similar needs.


On Sep 25, 2017 6:09 PM, "Thomas Haller" <notifications@github.com> wrote:

Well, with the patch in the current form, you could not extend the "ip"
dictionary. But that wouldn't matter, because "ip" is a only a dictionary,
not a list. So instead of

  - name: "eth0"
    ...
    ip:
       foo_bar: value

you'd have to do:

network_connections:
  - name: "eth0"
    type: "ethernet"
    mac: "12:34:56:78:9a:bc"
    ip:
        dhcp4: yes
    user_attrs:
        libvirt_dev: eno1.2
        ip:
            foo_bar: value

or

    user_attrs:
        libvirt_dev: eno1.2
        ip_foo_bar: value

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/linux-system-roles/network/issues/15#issuecomment-332028459>,
or mute the thread

**Comment by thom311** [comment]
I think now this is not a useful thing to do.

I closed https://github.com/linux-system-roles/network/pull/16 , and closing this as well.

If you still think something should be done about this, please reopen and explain.

Thanks
