### ISSUE TITLE
Checkpoint is not reverted when role aborts with log_error()

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#154]
`log_error()` does not only log but also exists the module. In this case, the role does not yet revert the checkpoint. This needs to be changed.

**Comment by pcahyna** [comment]
does it mean that  #119 introduced a regression? Or did it just expose a bug present before?

**Comment by pcahyna** [comment]
Instead of fixing the module so that it always reverts the checkpoint, wouldn't it be better to let NM itself revert the checkpoint (after a timeout)? There can always be unforeseen circumstances where the module would abort, so letting NM revert the checkpoint would be more robust.

**Comment by tyll** [comment]
> does it mean that #119 introduced a regression? Or did it just expose a bug present before?

Previously the role did not use checkpoints and the new implementation is faulty.

> Instead of fixing the module so that it always reverts the checkpoint, wouldn't it be better to let NM itself revert the checkpoint (after a timeout)? There can always be unforeseen circumstances where the module would abort, so letting NM revert the checkpoint would be more robust.

There is also a timeout that will revert the checkpoint eventually. But in the meantime a possibly partial configuration might be active and the role will fail until the checkpoint is taken care of. Reference:
https://github.com/linux-system-roles/network/blob/master/library/network_connections.py#L1895

**Comment by pcahyna** [comment]
Symptom: when the role fails (for whatever reason), subsequent invocation fails with a message like
```
msg: 'fatal error: failure to checkpoint_create checkpoint: nm-manager-error-quark: device ''lo'' is already included in checkpoint /org/freedesktop/NetworkManager/Checkpoint/268 (12): {''error'': "nm-manager-error-quark: device ''lo'' is already included in checkpoint /org/freedesktop/NetworkManager/Checkpoint/268 (12)", ''success'': None}'
```
Workaround: wait 90 seconds for each profile one specified when the role failed originally.
(from #190)

**Comment by tyll** [comment]
@9minds thank you for closing #190. Could you maybe share how you triggered the failure? It might help to add a test case.

**Comment by tyll** [comment]
Related bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1816140

**Comment by tyll** [comment]
> Workaround: wait 90 seconds for each profile one specified when the role failed originally.
> (from #190)

Another workaround:

1. Get the name/ID of the checkpoint:

`gdbus introspect --system --dest org.freedesktop.NetworkManager --object-path /org/freedesktop/NetworkManager/Checkpoint --recurse | awk '/^ *node /{print $2}'`

2. Revert it:

`gdbus call --system  --dest org.freedesktop.NetworkManager --object-path /org/freedesktop/NetworkManager --method org.freedesktop.NetworkManager.CheckpointRollback /org/freedesktop/NetworkManager/Checkpoint/66`
