### ISSUE TITLE
Update tests_default to new standard

### ISSUE THREAD

**Issue by a-mere-peasant** [linux-system-roles/network#161]
The old tests need to be updated so they are consistent with the new standards

**Comment by a-mere-peasant** [comment]
I've started working on this, #160 should update the default test

**Comment by pcahyna** [comment]
What "new standards" are you referring to? Can you please provide a link?

**Comment by a-mere-peasant** [comment]
I meant to be consistent with the ones that were written /updated recently like [tests_ethool_features_nm.yml](https://github.com/linux-system-roles/network/blob/master/tests/tests_ethtool_features_nm.yml)
,basically use the same format as these new ones .

I was trying to work on [GSoC wiki](https://github.com/linux-system-roles/network/wiki) .

I now realize I should have worded that properly . Should I just write "old tests need to be consistent with the new ones " ? 

Thanks for looking into this ,Please do let me know if anything else is to be changed or corrected .

**Comment by a-mere-peasant** [comment]
i've updated the other two , #162 should make these more consistent

**Comment by a-mere-peasant** [comment]
#164 should resolve this
