### ISSUE TITLE
Support for ETHTOOL_OPTS such as ethtool -K|--features|--offload and others

### ISSUE THREAD

**Issue by hartsjc** [linux-system-roles/network#17]
Currently there is no way via ansible to support device specific options set via ethtool command.  This allows for setting a variety of NIC parameters from speed, duplex, variety offloads, and even buffers.  modifying these values is critical to network performance in many enterprise environments, and thus would be good if linux-system-roles supported configuring them.

**Comment by hartsjc** [comment]
Issue 10 was closed as too generic.  Thus guessing issue 9 will soon follow.  Thus opening this issue as Ethtool Ops is a current need/request from enterprise customer.

**Comment by thom311** [comment]
`initscripts` accept the `ETHTOOL_OPTS` variable, which is just passed on to `ethtool`.

NetworkManager wouldn't allow an opaque string, it only supports ethtool options that it actually understands an implements. For what it's worth, systemd-networkd would behave just the same. I also think what initscripts do is very ugly, and NetworkManager is right here.

It also means, that NetworkManager currently does not support every option which ethtool (or initscripts) supports.

Regardless of whether NetworkManager is doing it right or not, it also follows that the role must understand each ethtool option, since it otherwise wouldn't know how to configure it in NetworkManager.

You already mention speed, duplex, etc. Could you provide the exact list of options that you request, preferably sorted by priority? Or just specify a few most interesting options first, and address the rest later. Thanks.

**Comment by hartsjc** [comment]
First three would be good start..
1. speed
2. duplex
3. autoneg
4. -G (tx/rx ring)
5. -K (features)
6. -C (coalesce)

Since ETHTOOL_OPT is really pretty free form, would be nice to allow that in playbook too.  Maybe as an append to those that have matching NM sets.

**Comment by thom311** [comment]
> -G (tx/rx ring)
> -K (features)
> -C (coalesce)

the problem with these options is that they are not supported by NetworkManager. While I am fine with adding options that are only understood by `nm` but not by `initscripts`, I'd rather not add any options that won't work with NetworkManager. If these are strongly requested, then there should also be a feature request to add them to NetworkManager. It seems to me, if they are not important enough to add to NetworkManager, they are not important enough for the ansible role either. Please open a feature request against NetworkManager.

> Since ETHTOOL_OPT is really pretty free form, would be nice to allow that in playbook too. Maybe as an append to those that have matching NM sets.

I dislike the idea of having an unstructured `ETHTOOL_OPTS` field that is passed on blindly. The role should understand all options. Of course, the role could parse `ETHTOOL_OPTS` and validate it (according to the options it supports). But if the role already implements these features, I'd rather not express them in configuration as an `ETHTOOL_OPTS` string, but as a structured, nested option.

Pull request #24 adds support for `autonet`, `speed`, and `duplex`. Both for `initscripts` and `nm`. Let's do that first, and see what is required next.

**Comment by thom311** [comment]
#24 got merged and "autoneg", "speed", "duplex" added.

Leave issue open for other ethtool options.

**Comment by pcahyna** [comment]
Docmentation of the options added in #24 is proposed in #36. Please review.

**Comment by thom311** [comment]
> There is also https://bugzilla.redhat.com/show_bug.cgi?id=1335409 ...
>
> I'd still prefer to see that the features get added to NetworkManager first, and then here.

Arguably, there isn't really a problem with adding support for further options in initscripts only... until NM supports them. That means, contrary to how I made it sound before, I think the initscripts part is not blocking on NetworkManager support.

**Comment by tyll** [comment]
Do you have any preferences or ideas how to represent the options in the role settings? How about:

```yaml
network_connections:
  - name: eth0
    type: ethernet
    ethernet:
        features:
            tx: "no"
           esp_hw_offload: "yes"
           [...]
```

**Comment by pcahyna** [comment]
`features` sounds way too generic. Anything is a feature, no? What about `offload`? (if you mean the options that translate to `ethtool -K`)
Is there some precedent in some other management software or standard?

**Comment by tyll** [comment]
> `features` sounds way too generic. Anything is a feature, no? What about `offload`? (if you mean the options that translate to `ethtool -K`)

It is in the ethernet subtree, which distinguishes them from other features. `man ethtool` mentions `--features` as first long option for `-K` and it also says:

`Changes the offload parameters and other features of the specified network device.` which seems to indicate that its not only offload features.

> Is there some precedent in some other management software or standard?

I guess ethtool is the management software for this.

**Comment by pcahyna** [comment]
How are those properties called in NetworkManager? Or is there some SNMP MIB for them?

**Comment by tyll** [comment]
> How are those properties called in NetworkManager? Or is there some SNMP MIB for them?

There is no documentation about them in NM (AFAIK), they are prefixed with ethtool.feature in nmcli, for example: `nmcli connection modify "$PROFILE" ethtool.feature-lro off`. I did not find any trace for an SNMP MIB for these settings.

**Comment by tyll** [comment]
@pcahyna do we want to use dictionary keys with dashes in the profile, for example:
https://github.com/linux-system-roles/network/pull/115/files#diff-99808dc08023d67609805bd6f6cca8ecR20
`tx-sctp-segmentation`  (this is how ethtool accepts it), or do we prefer underscores (`tx_sctp_segmentation`)? The dashes seem to irritate the vim yaml syntax hightlight plugin.

**Comment by pcahyna** [comment]
Should they really be in the ethernet subtree? The notion of upper layer checksum/segment/whatever offload seems to be fairly link-layer independent and it seems more like a historical accident that one uses `ethtool` to set those features. https://www.mjmwired.net/kernel/Documentation/infiniband/ipoib.txt#53

**Comment by tyll** [comment]
@thom311 @hartsjc do you maybe have suggestions for naming/organizing the subtree? Other idea were device_features at the top level or an ethtool subtree with an features subtree.

**Comment by hartsjc** [comment]
Should support network.service (ifcfg) & NetworkManager, right?  If so, I don't see need to tie it to NetworkManager style.  Honestly the ETHTOOL_OPTS= that ifcfg uses may make more sense.

**Comment by tyll** [comment]
> Should support network.service (ifcfg) & NetworkManager, right? If so, I don't see need to tie it to NetworkManager style. Honestly the ETHTOOL_OPTS= that ifcfg uses may make more sense.

Thank you for your feedback. Since it is about configuring an Ansible role, I do not see how EHTTOOL_OPTS would fit in here. Making it a string option in ansible with different values would make it harder to use Ansible features such as filters or the inventory to enable/disable/ignore features based on other conditions. Therefore using a dictionary with boolean values seems to make more sense to me.

**Comment by hartsjc** [comment]
Thought were asking about the features discussion, and thought prefixing it with ethtool like used to in ifcfg files would be possibility.  But however feature is implemented doesn't matter to me, just will be good to have this feature available.

**Comment by tyll** [comment]
> Thought were asking about the features discussion, and thought prefixing it with ethtool like used to in ifcfg files would be possibility. But however feature is implemented doesn't matter to me, just will be good to have this feature available.

Not sure, maybe I misunderstood you - did you mean something like the following?

```yaml
network_connections:
  - name: eth0
    type: ethernet
    ethtool:
        features:
            tx: "no"
            esp_hw_offload: "yes"
           [...]
```

I understood you meant something like:
```yaml
network_connections:
  - name: eth0
    type: ethernet
    ethtool_opts: "-k eth0 tx off esp_hw_offload on"
```

This would be doing it like ifcfg files with the downsides I described.

**Comment by pcahyna** [comment]
I would use just a `features` dict directly under the connection dict. `ethtool` is just the name of the tool used to get/set the features that might soon become legacy (if setting/getting is implemented in iproute), so I would not introduce the name in the API. I said previously that `features` sounds a bit too generic, but it seems to be used for those settings pretty consistently, so why not.

**Comment by thom311** [comment]
FWIW, I would use this:
```yaml
network_connections:
  - name: eth0
    type: ethernet
    ethtool:
        features:
            tx: "no"
            esp_hw_offload: "yes"
           [...]
```
This is also how it looks to NetworkManager.

"features" as a name alone seems too generic, I would nest it under "ethtool" so that it can be beside the other RFCs for coalesce and ring options.

**Comment by pcahyna** [comment]
I am ok with nesting under `ethtool`, if @thom311 and @tyll agree on it. While I think it is suboptimal to name it after one tool (itself rather misnamed), the name is already quite pervasive, even in the kernel.
