### ISSUE TITLE
Write a contributing document

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#192]
Topics to be included, they can be added incrementally:

- [x] How to run the unit tests/static tests (tox)
- [x] How to run the integration tests locally
- [x] Some overview how the code is structured
- [x] Code conventions like pep8 and black
- [x] Naming conventions from https://github.com/oasis-roles/meta_standards#naming-things
- [x] How to write commit messages as described in https://chris.beams.io/posts/git-commit (#204)
- [x] Git config for username and e-mail address
- [x] How to rebase PRs
- [x] How the CI integration tests are triggered
- [x] Mention the mailing list and IRC channel
- [x] Mention the targetted Python version (2.6, 2.7, 3.6, 3.7 and 3.8) at the momen.
- [ ] Anything else

Some content can be re-used from https://github.com/linux-system-roles/network/wiki

**Comment by a-mere-peasant** [comment]
for the commit message part
- writing the seven rules 
- a sample message as written the article or [subsurface-for-dirk contributing](https://github.com/torvalds/subsurface-for-dirk/blob/master/README.md#contributing) (this is also linked in the article ) and 
- a link to the article for detailed instructions or further reading 

should be good enough ?

**Comment by tyll** [comment]
> for the commit message part
> 
> * writing the seven rules
> * a sample message as written the article or [subsurface-for-dirk contributing](https://github.com/torvalds/subsurface-for-dirk/blob/master/README.md#contributing) (this is also linked in the article ) and
> * a link to the article for detailed instructions or further reading
> 
> should be good enough ?

yes, this sounds good.

**Comment by a-mere-peasant** [comment]
will it be okay to just use the sample message used in the blog ?

**Comment by ffmancera** [comment]
I think this is done, right? @tyll
