### ISSUE TITLE
Implement ethtool's GPERMADDR in python instead of using the ethtool command-line tool

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#199]
Instead of using the ethtool command-line tool. python can directly talk with the kernel as nmstate does in https://github.com/nmstate/nmstate/blob/master/libnmstate/ethtool.py

This will fix bugs as #130 and #39 

Tasks:
- [ ] Implement the required ethtool feature in python as a new python module in `module_utils/network_lsr` and use it instead of the command-line utility
- [ ] remove installing the ethtool command-line tool from the tasks
- [ ] make sure that all issues are closed by the PR, inlcuding #130 and #39 if they are still open

References:
https://github.com/torvalds/linux/blob/master/include/uapi/linux/ethtool.h#L1388
https://github.com/torvalds/linux/blob/master/include/uapi/linux/ethtool.h#L734

**Comment by ffmancera** [comment]
I would like to work on this. Thanks.
