### ISSUE TITLE
802.1x: Support domain-suffix-match setting

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#201]
This might conflict with the renaming as of #189 

Bonus tasks: Add other 802.1x settings from NM that would be easy to add.

**Comment by tyll** [comment]
@jaedolph it would be great if you have the time to look at this.

**Comment by jaedolph** [comment]
@tyll I will have a look at this

**Comment by jaedolph** [comment]
Have created PR #212 to address this
