### ISSUE TITLE
Warn or fail if `persistent_state` is present and state is set to present or absent.

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#205]
If both `persistent_state` and `state` are set for a profile, allowing state should not be specified or `up` or `down`. Setting it to `absent` or `present` would be a mistake and indicates a problem. It happened in the past, see: https://github.com/linux-system-roles/network/pull/196/commits/fbf79ac3a0e81e5a94bc5ef3d649e741edba1158

**Comment by elvgarrui** [comment]
I'm willing to complete this but I have a question: Do you mean that if persistent_state is set then state can only be up or down? I'm a bit confused by the message issue.

**Comment by tyll** [comment]
> I'm willing to complete this but I have a question: Do you mean that if persistent_state is set then state can only be up or down? I'm a bit confused by the message issue.

Basicaslly, yes: if persistent_state is set then state can only be up, down or not be specified.

**Comment by elvgarrui** [comment]
Should we close this issue now?

**Comment by tyll** [comment]
yes, thanks
