### ISSUE TITLE
RFE: Support dummy interfaces

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#210]
Support dummy interfaces that can be created with nmcli like this:
`nmcli con add type dummy ifname dummy0 ipv4.addresses 192.0.2.42/30`

**Comment by salderma** [comment]
I could really use this feature.  Also, I'd be happy to contribute to this feature.  

I'm not entirely sure where I should be starting though, can I get a little coaching and a shove in the right direction?

**Comment by jaedolph** [comment]
Hi @salderma, there is a contributing guide here: https://github.com/linux-system-roles/network/blob/main/contributing.md

You could look at some of the closed PRs for other feature branches if you want some inspiration on where to start:
https://github.com/linux-system-roles/network/pull/27
https://github.com/linux-system-roles/network/pull/159

**Comment by tyll** [comment]
@salderma are you still interested in working on this?

**Comment by salderma** [comment]
I think we would still like to see the feature added, but I do not have the bandwidth to get up to speed and add it myself unfortunately.

**Comment by liangwen12year** [comment]
updated here, https://github.com/linux-system-roles/network/pull/324
