### ISSUE TITLE
Service facts seem to fail on Fedora 32

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#218]
https://fedorapeople.org/groups/linuxsystemroles/logs/linux-system-roles-network-pull-linux-system-roles_network-200-2b7e16a-fedora-32-20200506-161452/artifacts/ansible.log

```
TASK [linux-system-roles.network : Check which services are running] ***********
task path: /tmp/tmpj7fr713o/tests/roles/linux-system-roles.network/tasks/main.yml:4
fatal: [/cache/Fedora-Cloud-Base-32-1.6.x86_64.qcow2]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
```

Ideally, we should get rid of the service_facts module and implement a custom module that checks the system and determines what we need to know. This might be reported at some point. However, it would be great to fix Fedora 32 rather, soon, regardless of this.

**Comment by tyll** [comment]
```
TEST_SUBJECTS=~/cloud-images/Fedora-Cloud-Base-32-1.6.x86_64.qcow2 ansible -i /usr/share/ansible/inventory/standard-inventory-qcow2 -m service_facts all
/home/till/cloud-images/Fedora-Cloud-Base-32-1.6.x86_64.qcow2 | FAILED! => {
    "changed": false,
    "msg": "Malformed output discovered from systemd list-unit-files: arp-ethers.service                             disabled        disabled     "
}
```

**Comment by pcahyna** [comment]
> Ideally, we should get rid of the service_facts module and implement a custom module that checks the system and determines what we need to know.

Wouldn't it be better to fix the service_facts module, so that all Ansible/Fedora users can benefit from the fix, instead of reimplementing it?

**Comment by tyll** [comment]
> > Ideally, we should get rid of the service_facts module and implement a custom module that checks the system and determines what we need to know.
> 
> Wouldn't it be better to fix the service_facts module, so that all Ansible/Fedora users can benefit from the fix, instead of reimplementing it?

I just checked, it is fixed in the upstream devel branch. I tested commit 366f80868339936521af26d4dfba53dd5f92126e

**Comment by pcahyna** [comment]
Relevant references: https://github.com/ansible/ansible/pull/68211 https://github.com/ansible/ansible/issues/68536 https://github.com/ansible/ansible/issues/69302 https://github.com/ansible/ansible/pull/69303

**Comment by ajacocks** [comment]
Verified that this works again, on stable-2.9.

**Comment by tyll** [comment]
The Ansible update is in Fedora 32 stable, so it is not as important anymore.
