### ISSUE TITLE
RFE: 802.1x support ca-path setting

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#229]
Add support for the ca-path NM setting:
https://developer.gnome.org/NetworkManager/stable/nm-settings.html#nm-settings.property.802-1x.ca-path

**Comment by tyll** [comment]
@jaedolph are you interested in doing this?

**Comment by jaedolph** [comment]
@tyll sure thing, I'll have a look at it this weekend

**Comment by jaedolph** [comment]
Have implement this in a new PR, but the actual ca-path setting itself doesn't appear to work in NetworkManager. Have raised a bug here: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/448 

@thom311 do you have any ideas?
