### ISSUE TITLE
add better error message in case NetworkManager-wifi is not installed and network_allow_restart is not specified.

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#244]
Currently, the role will just fail in case NetworkManager-wifi is missing and network_allow_restart is not specified. It would be nice to add a proper error message and tests for this case. Currently, the test specifies network_allow_restart.

**Comment by marituhone** [comment]
@tyll  can you assign me this  task please

**Comment by tyll** [comment]
@liangwen12year is already working on this in #675

**Comment by marituhone** [comment]
@tyll   so i cant work on this issue?

**Comment by liangwen12year** [comment]
> @tyll so i can't work on this issue?

Right, the PR was already merged.
