### ISSUE TITLE
Document how to run the integration tests with podman

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#280]
Document in the contribution guideline how to run the integration tests with podman

```

cd ~/.ansible/collections/ansible_collections/containers/podman/

git clone https://github.com/containers/ansible-podman-collections.git .

cd ~/network-lsr/tests

podman run --name c8 --rm --privileged  -v
/sys/fs/cgroup:/sys/fs/cgroup:ro docker.io/nmstate/centos8-nmstate-dev

ansible-playbook -vi "c8," -c containers.podman.podman tests_provider.yml

```

Please note that at least the wifi or 802.1x tests does not work because
they use network namespaces and that seemed to be a problem. Also it
might be that running CentOS 7 containers do not work on Fedora with
systemd because of cgroups v2. And it might be possible to use the
systemd centos container image that you found instead of the nmstate
one (did not try).

**Comment by liangwen12year** [comment]
## How to run the integration tests with Podman

1. Change the directory into Podman module.
'''
cd ~/.ansible/collections/ansible_collections/containers/podman/
'''

2. Clone the containers for Ansible-Podman into the current directory.
'''
git clone https://github.com/containers/ansible-podman-collections.git .
'''

3.  Change directory into the test folder.
'''
cd ~/network-lsr/tests
'''

4. Run the process in a new container with Podman and configure the running process.
'''
podman run --name c8 --rm --privileged  -v
/sys/fs/cgroup:/sys/fs/cgroup:ro docker.io/nmstate/centos8-nmstate-dev
'''

5.  Use  Ansible playbook to run it as inventory on the containers.
'''
ansible-playbook -vi "c8," -c containers.podman.podman tests_provider.yml
'''

**Comment by liangwen12year** [comment]
## How to run the integration tests with Podman
1. Change the directory into Podman module.

```
cd ~/.ansible/collections/ansible_collections/containers/podman/
```


2. Clone the containers for Ansible-Podman into the current directory.
```
git clone https://github.com/containers/ansible-podman-collections.git .
```

3. Change directory into the test folder.
```
cd ~/network-lsr/tests
```

4. Run the process in a new container with Podman and configure the running process.
```
podman run --name c8 --rm --privileged -v
/sys/fs/cgroup:/sys/fs/cgroup:ro docker.io/nmstate/centos8-nmstate-dev
```

5. Use Ansible playbook to run it as inventory on the containers.
```
ansible-playbook -vi "c8," -c containers.podman.podman tests_provider.yml
```

**Comment by tyll** [comment]
Please try this container image instead of the nmstate one: "registry.centos.org/centos/systemd:latest"

**Comment by liangwen12year** [comment]
sure, I will try

**Comment by richm** [comment]
This is what I did:
```
podman run --name c7 --rm --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -d registry.centos.org/centos/systemd
ansible-playbook -vi c7, -c podman tests_provider_nm.yml
PLAY [Run playbook 'playbooks/tests_provider.yml' with nm as provider] *********

TASK [Gathering Facts] *********************************************************
Failed to mount container c7: b'Error: cannot run command "podman mount" in rootless mode, must execute `podman unshare` first'
[WARNING]: Unhandled error in Python interpreter discovery for host c7:
Expecting value: line 1 column 1 (char 0)
[WARNING]: Platform linux on host c7 is using the discovered Python interpreter
at /usr/bin/python, but future installation of another Python interpreter could
change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/inte
rpreter_discovery.html for more information.
ok: [c7]
...
PLAY RECAP *********************************************************************
c7                         : ok=4    changed=2    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0   
```
Note - use podman with `-d` to run in the background (daemon).  Use `c7` because `centos/systemd` is centos7.  Use `-c podman` because https://docs.ansible.com/ansible/latest/plugins/connection.html

NOTE that this leaves the container running in the background - to kill it:
```
> podman ps
CONTAINER ID  IMAGE                                      COMMAND         CREATED         STATUS             PORTS   NAMES
bb869fa10290  registry.centos.org/centos/systemd:latest  /usr/sbin/init  11 minutes ago  Up 11 minutes ago          c7
> podman stop bb869fa10290
> podman rm bb869fa10290
```
