### ISSUE TITLE
Providing example for MAC VTAP

### ISSUE THREAD

**Issue by cathay4t** [linux-system-roles/network#285]
Currently, we are supporting MAC VTAP as `"tap": True` in `macvlan`. It should be well documented with examples.

**Comment by marituhone** [comment]
@ffmancera  @cathay4t  @richm  am i suppose to do the doc  in the Readme.md  or is it required to be done on examples and create  MAC VTAP.yml

**Comment by cathay4t** [comment]
For nmstate backend, I would suggest you to redirect user to nmstate.io

**Comment by marituhone** [comment]
@cathay4t   i am bit confused can u make it clear, am working on the issue and i prepare a doc for developer on how  Macvtap interface can be created using the ip command but when i  explore the repo i have seen examples directory.. so does this issue  need Macvtap.yml  or developer doc am confused b/n the 2.

**Comment by cathay4t** [comment]
Sorry. My initial intention is for `network_connections` backend, not nmstate.

Please take `examples/macvlan.yml` as example, the MAC TAP is just changing it to `tap: true`.

**Comment by marituhone** [comment]
@cathay4t  can you review my PR please
