### ISSUE TITLE
802.1x tests fail in CI

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#286]
The error is:

```
TASK [linux-system-roles.network : Show debug messages] ************************
task path: /tmp/tmpu70vy5o6/tests/roles/linux-system-roles.network/tasks/main.yml:89
ok: [/cache/Fedora-Cloud-Base-32-1.6.x86_64.qcow2] => {
    "__network_connections_result": {
        "_invocation": {
            "module_args": {
                "__debug_flags": "", 
                "connections": [
                    {
                        "name": "802-1x-test", 
                        "persistent_state": "absent", 
                        "state": "down"
                    }, 
                    {
                        "name": "br1", 
                        "persistent_state": "absent", 
                        "state": "down"
                    }
                ], 
                "force_state_change": false, 
                "ignore_errors": false, 
                "provider": "nm"
            }
        }, 
        "changed": true, 
        "failed": false, 
        "stderr": "[005] <info>  #0, state:down persistent_state:absent, '802-1x-test': down connection 802-1x-test failed: connection not found\n[006] <info>  #1, state:down persistent_state:absent, 'br1': down connection br1: /org/freedesktop/NetworkManager/ActiveConnection/2\n[007] <info>  #0, state:down persistent_state:absent, '802-1x-test': no connection '802-1x-test'\n[008] <info>  #1, state:down persistent_state:absent, 'br1': delete connection br1, a688210f-9e86-4592-85cc-42b2d32faeca\n[009] <info>  #1, state:down persistent_state:absent, 'br1': delete connection br1, 84b50f27-2fcc-4a4b-9fce-2667c2cf55c6\n", 
        "stderr_lines": [
            "[005] <info>  #0, state:down persistent_state:absent, '802-1x-test': down connection 802-1x-test failed: connection not found", 
            "[006] <info>  #1, state:down persistent_state:absent, 'br1': down connection br1: /org/freedesktop/NetworkManager/ActiveConnection/2", 
            "[007] <info>  #0, state:down persistent_state:absent, '802-1x-test': no connection '802-1x-test'", 
            "[008] <info>  #1, state:down persistent_state:absent, 'br1': delete connection br1, a688210f-9e86-4592-85cc-42b2d32faeca", 
            "[009] <info>  #1, state:down persistent_state:absent, 'br1': delete connection br1, 84b50f27-2fcc-4a4b-9fce-2667c2cf55c6"
        ]
    }
}
```

**Comment by pcahyna** [comment]
I saw "connection not found" or other possibly related errors in other tests as well. Not just 802.1x. IIRC bridge and/or bonds were among the affected, but it seemed quite intermittent. Here is a failure in tests_integration_pytest on fedora-31, I saw this twice. https://fedorapeople.org/groups/linuxsystemroles/logs/linux-system-roles-network-pull-linux-system-roles_network-282-4d705e3-fedora-31-20200908-125733/artifacts/test.log.html . Error is "Exception: cannot read stable link-infos. They keep changing".

**Comment by pcahyna** [comment]
Another is here:
https://fedorapeople.org/groups/linuxsystemroles/logs/linux-system-roles-network-pull-linux-system-roles_network-282-4d705e3-centos-7-20200908-135709/artifacts/test.log.html
```
 "stderr": "[003] <info>  #0, state:down persistent_state:absent, 'wlan0': down connection wlan0 failed: connection not found\n[004] <info>  #0, state:down persistent_state:absent, 'wlan0': no connection 'wlan0'\n"
```

**Comment by cathay4t** [comment]
Should be fixed by PR #286

**Comment by jaedolph** [comment]
Had a look at this and it appears to be a problem with role not starting wpa_supplicant (which is required for 802.1x connections) on fedora32. I'm guessing there are issues evaluating the `__network_ieee802_1x_connections_defined` variable. Will look in to this.

Relevant logs in the CI:
```
TASK [linux-system-roles.network : Enable and start wpa_supplicant] ************
task path: /tmp/tmp5zsof_3m/tests/roles/linux-system-roles.network/tasks/main.yml:55
skipping: [/cache/Fedora-Cloud-Base-32-1.6.x86_64.qcow2] => {"changed": false, "skip_reason": "Conditional result was False"}
```

**Comment by jaedolph** [comment]
Had a bit more of a look at this. Seems to be the same issues with service_facts being broken on F32.

Using ansible 2.8.16 on F32, the service facts module throws an exception (this bugfix has not been backported https://github.com/ansible/ansible/commit/fbf93db4a8c7c5f70dc516fb9f96138180eabf56#diff-3e357c83f6315d6f19b61632d147d70c37ddaecf9e0ecfb1864a899c0aeef72d)

Using ansible 2.9.13 on F32, the bug has been fixed but for some reason ansible can't detect the state of the wpa_supplicant service:
```
TASK [linux-system-roles.network : Enable and start wpa_supplicant] ************
task path: /tmp/tmp437cznrs/tests/roles/linux-system-roles.network/tasks/main.yml:55
fatal: [/cache/Fedora-Cloud-Base-32-1.6.x86_64.qcow2]: FAILED! => {"changed": false, "msg": "Service is in unknown state", "status": {}}
```

**Comment by richm** [comment]
I think this is the problem
```
Fedora-Cloud-Base-32-1.6.x86_64.qcow2
```
i.e. this is the original Fedora 32 image.  In staging we are using the latest published Fedora cloud image rebuild: https://fedorapeople.org/groups/linuxsystemroles/logs/linux-system-roles-network-pull-linux-system-roles_network-311-955d6e1-fedora-32-20201030-014800/artifacts/test.log.html `Fedora-Cloud-Base-32-20201029.0.x86_64.qcow2`
@pcahyna @jharuda if staging has no other problems we should update production CI from staging
