### ISSUE TITLE
[RFE] refactor logging of network module

### ISSUE THREAD

**Issue by thom311** [linux-system-roles/network#29]
Currently, the module collects all logging statements, and at the end returns them as "warnings", so that they are shown by ansible. Obviously, these are not really warnings, but rather debug information.

Instead, the logging messages should be returned in a different json field that is ignored by ansible. Then, the `tasks/main.yml` should have a follow-up `debug` task that prints the returned variable.

I guess, in the failure case, the `network_connections` task must run ignoring failures to reach the `debug` statement. Then, a follow up task should check whether the `network_connections` task failed and abort.

**Comment by tyll** [comment]
Ansible now supports blocks and the messages could be shown in the rescue or always part in case of failures. Reference: https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html

**Comment by tyll** [comment]
Actually in case of a failure, the module can just output the logs as warnings as currently in addition to putting them into a different json field. No need for a rescue block IMHO.  The debug statement might be nice nonetheless.
