### ISSUE TITLE
Query for VDO

### ISSUE THREAD

**Issue by taru-svg** [linux-system-roles/network#290]
When is it planned to provide VDO (Virtual Disk Optimizer) feature in rhel 7

#289 #vdo #query #rhel7 @richm @seocam @laddp @dsedivec @bengal

**Comment by pcahyna** [comment]
Sorry, this is a repository for an Ansible role for networking and not at all the right place to ask about VDO support or any other support questions about RHEL.

**Comment by taru-svg** [comment]
Can you please redirect me to the right repository, I am new to it.
Thanks
