### ISSUE TITLE
Add test testing that NetworkManager plugins are being installed correctly

### ISSUE THREAD

**Issue by ffmancera** [linux-system-roles/network#305]
When creating a WIFI interface network-role will install NetworkManager-wifi and when creating a Team interface, network-role will install NetworkManager-team.

This need to be tested. In order to do it, I recommend you to implement the following procedure:

1. Uninstall the package (NetworkManager-team or NetworkManager-wifi)
2. Create the interface
3. Check if the package is installed

The expected result will be 2 tests that are checking that both packages are being installed correctly by network-role

**Comment by liangwen12year** [comment]
updated here, https://github.com/linux-system-roles/network/pull/308
