### ISSUE TITLE
Use `setup_module_utils.sh` from storage role for module import path issue of test

### ISSUE THREAD

**Issue by cathay4t** [linux-system-roles/network#306]
Uses the setup_module_utils.sh script
instead of having the tests rewrite the module import path.

e.g. like the storage role which also uses module_utils
https://github.com/linux-system-roles/storage/blob/master/.travis/config.sh#L61

and the kernel_settings role
https://github.com/linux-system-roles/kernel_settings/blob/master/.travis/config.sh#L60

**Comment by tyll** [comment]
I believe this is handled somehow by tox-lsr, which is also something that is under dispute (see #411).
