### ISSUE TITLE
Skip the test for initscripts provider on RHEL/CentOS 8 and Fedora.

### ISSUE THREAD

**Issue by cathay4t** [linux-system-roles/network#332]
There is no need to test initscripts provider on RHEL/CentOS 8 and Fedora where it is deprecated.

**Comment by cathay4t** [comment]
@liangwen12year Would like to take this task on?

**Comment by liangwen12year** [comment]
sure

**Comment by tyll** [comment]
initscripts is still supported on RHEL/CentOS 8 and Fedora, therefore it should still be tested IMHO.

**Comment by cathay4t** [comment]
OK. If deprecate means still support. I am OK to keep it in CI.
