### ISSUE TITLE
Tox failed in "main" branch

### ISSUE THREAD

**Issue by liangwen12year** [linux-system-roles/network#339]
```
[wenliang@localhost network]$ tox
ERROR: No pyproject.toml or setup.py file found. The expected locations are:
  /home/wenliang/network/pyproject.toml or /home/wenliang/network/setup.py
You can
  1. Create one:
     https://tox.readthedocs.io/en/latest/example/package.html
  2. Configure tox to avoid running sdist:
     https://tox.readthedocs.io/en/latest/example/general.html
  3. Configure tox to use an isolated_build
  ```

**Comment by richm** [comment]
> ```
> [wenliang@localhost network]$ tox
> ERROR: No pyproject.toml or setup.py file found. The expected locations are:
>   /home/wenliang/network/pyproject.toml or /home/wenliang/network/setup.py
> You can
>   1. Create one:
>      https://tox.readthedocs.io/en/latest/example/package.html
>   2. Configure tox to avoid running sdist:
>      https://tox.readthedocs.io/en/latest/example/general.html
>   3. Configure tox to use an isolated_build
> ```

https://linux-system-roles.github.io/contribute.html "Using tox and tox-lsr"
