### ISSUE TITLE
Error during "Install packages" phase 

### ISSUE THREAD

**Issue by debuggercz** [linux-system-roles/network#348]
Hi all,

I have probably elementary question but I can't find out where is the problem. I tried to apply install linux-system-roles.network role on the latest CentOS 7.9 with the latest NM API available in CentOS repository. My first attempt for only remove old profile:

network_connections:
  - name: enp97s0f0
    persistent_state: absent

but I get following error.

TASK [linux-system-roles.network : Install packages] ****************************************************************************************
fatal: [server]: FAILED! => {"msg": "The conditional check 'not network_packages is subset(ansible_facts.packages.keys())' failed. The error was: An unhandled exception occurred while templating '{{ __network_provider_setup[network_provider]['packages'] }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{u'initscripts': {u'service_name': u'{{ __network_service_name_default_initscripts }}', u'packages': u'{{ __network_packages_default_initscripts }}'}, u'nm': {u'service_name': u'{{ __network_service_name_default_nm }}', u'packages': u'{{ __network_packages_default_nm }}'}}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ __network_packages_default_initscripts_bridge|select()|list() + __network_packages_default_initscripts_network_scripts|select()|list() }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '[u\"{% if ['bridge'] in network_connections|json_query('[*][type]') and ansible_distribution in ['RedHat', 'CentOS', 'OracleLinux'] and ansible_distribution_major_version is version('7', '<=') %}bridge-utils{% endif %}\"]'. Error was a <class 'ansible.errors.AnsibleError'>, original message: You need to install \"jmespath\" prior to running json_query filter\n\nThe error appears to be in '/home/debuggercz/.ansible/roles/linux-system-roles.network/tasks/main.yml': line 20, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# Therefore install packages only when rpm does not find them\n- name: Install packages\n  ^ here\n"}  

Packages from the server where I try manipulate with NM profiles:
rpm -qa | grep NetworkManager
NetworkManager-libnm-1.18.8-2.el7_9.x86_64
NetworkManager-1.18.8-2.el7_9.x86_64
NetworkManager-tui-1.18.8-2.el7_9.x86_64
NetworkManager-team-1.18.8-2.el7_9.x86_64
NetworkManager-libnm-devel-1.18.8-2.el7_9.x86_64

systemctl status NetworkManager
● NetworkManager.service - Network Manager
   Loaded: loaded (/usr/lib/systemd/system/NetworkManager.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-01-25 13:59:43 CET; 1 weeks 4 days ago
     Docs: man:NetworkManager(8)
 Main PID: 1268 (NetworkManager)
    Tasks: 5
   CGroup: /system.slice/NetworkManager.service
           ├─1268 /usr/sbin/NetworkManager --no-daemon
           ├─1311 /usr/bin/teamd -o -n -U -D -N -t external -c {"hwaddr": "40:A6:B7:1F:55:D0", "runner": {"name": "lacp", "tx_hash": ["eth", "ipv4", "ipv6"]}}
           └─3871 /sbin/dhclient -d -q -sf /usr/libexec/nm-dhcp-helper -pf /var/run/dhclient-external.pid -lf /var/lib/NetworkManager/dhclient-963ce2a3-00d0-4627-a4d1-2a036214d5ac-external.lease -cf /var/lib/N...

Could you please tell what I am doing wrong?

Thank you in advance
Michal

**Comment by richm** [comment]
What version of ansible are you using?  Is your control host Centos 7.9 or is your managed host Centos 7.9 or are both hosts Centos 7.9?
How did you install the linux-system-roles.network role?

**Comment by debuggercz** [comment]
On 2/5/21 6:33 PM, Richard Megginson wrote:
> What version of ansible are you using? Is your control host Centos 7.9
> or is your managed host Centos 7.9 or are both hosts Centos 7.9?
> How did you install the linux-system-roles.network role?

I am using ansible 2.9.17. On controll host is Linux Mint 19.3 and on
managed host(s) CentOS 7.

I used "ansible-galaxy install linux-system-roles.network" to install
the role.

Thank you
Michal

**Comment by richm** [comment]
From the error message: `You need to install "jmespath" prior to running json_query filter\`
Not sure how you install the python jmespath package on Linux Mint - e.g. on Fedora you would do `dnf install python3-jmespath`

**Comment by debuggercz** [comment]
I thought that jmespath must be ont the managed hosts. I installed the
package on controll host and it is working! Thank you very much for help

Michal
