### ISSUE TITLE
Add a Requirements section to README and add jmespath as a requirement

### ISSUE THREAD

**Issue by richm** [linux-system-roles/network#349]
The network role uses `json_query` which requires `jmespath` as an external dependency.  The README does not have a Requirements section (e.g. https://github.com/linux-system-roles/template#requirements). The README should add a Requirements section and add jmespath as a requirement.

Alternately, rewrite the role to use `selectattr` etc. instead of `json_query`.

See https://github.com/linux-system-roles/network/issues/348 for the type of error that can occur when jmespath is not present.

**Comment by tyll** [comment]
AFAIK, queries like https://github.com/linux-system-roles/network/blob/main/defaults/main.yml#L31 are not possible with `selectattr` or is it?

**Comment by richm** [comment]
> AFAIK, queries like https://github.com/linux-system-roles/network/blob/main/defaults/main.yml#L31 are not possible with selectattr or is it?

This would work even with ansible 2.8/jinja 2.7:
```
__network_wireless_connections_defined: "{{
      network_connections | selectattr('type', 'match', '^wireless$') | list | length > 0 }}"
```
