### ISSUE TITLE
[RFE] with NetworkManager try to use Reapply as a graceful way to change configuration

### ISSUE THREAD

**Issue by thom311** [linux-system-roles/network#38]
Currently, the role does the corresponding of `nmcli con up` when it notices changes to the profile. If the profile already is active, this caues NM to first tear the device down, before reactivating it. This is more disruptive than desired. The [`Reapply`](https://developer.gnome.org/NetworkManager/stable/gdbus-org.freedesktop.NetworkManager.Device.html#gdbus-method-org-freedesktop-NetworkManager-Device.Reapply) D-Bus command should be used where possible.

Note that with `Reapply`, NetworkManager first checks whether it can perform the desired actions, and abort with failure if it cannot (without touching the system). Hence, a suitable way to do this, is first try to reapply, and if that fails, fall back to full activation.

Note also, how reapply changes the ["applied-connection"](https://developer.gnome.org/NetworkManager/stable/gdbus-org.freedesktop.NetworkManager.Device.html#gdbus-method-org-freedesktop-NetworkManager-Device.GetAppliedConnection), and there is also a version-id, that allows to perform the reapply only, if the state is as expected. 

Maybe older NM versions don't yet sufficiently support Reapply. It needs to be seen whether the role needs some special handling.

**Comment by pcahyna** [comment]
@thom311 what are those older NM versions? I am especially interested in RHEL 7 support.

**Comment by thom311** [comment]
Reapply is supported for a long time already: 1.2.0.

RHEL-7 is now at 1.18.x, in the past there were some improvements to reapply, since it was introduced. But by now, it should work well (or bugs should be reported).
