### ISSUE TITLE
Update contributing document to include the need for tox-lsr

### ISSUE THREAD

**Issue by jaedolph** [linux-system-roles/network#382]
Now that tox tests are run with tox-lsr, the guide for running tests in the https://github.com/linux-system-roles/network/blob/main/contributing.md no longer works. Should update this to use the new method.

**Comment by tyll** [comment]
Since there is now a common contribution document the network one could link there for common things: https://linux-system-roles.github.io/contribute.html

**Comment by tyll** [comment]
Thanks, I agree.
