### ISSUE TITLE
Make verbose output optional

### ISSUE THREAD

**Issue by kwevers** [linux-system-roles/network#394]
The final debug statement in the tasks file can cause very lengthy output on systems with a lot of interfaces or a lot of routes.
It would be nice to have the option to disable this output or to change the default so that it only displays stderr/stderr_lines.
Would a PR for this be welcomed and what would be the preferred behavior?

https://github.com/linux-system-roles/network/blob/6fdac168a9406bbe2988245a2a77cfc48dfa51e0/tasks/main.yml#L91

**Comment by tyll** [comment]
this is a valid point. Showing only stderr_lines by default seems like a good idea and the full output with an extra `verbosity: 1` parameter so it requires `ansible-playbook`. What do you think about this? @richm what is your opinion?

**Comment by richm** [comment]
> this is a valid point. Showing only stderr_lines by default seems like a good idea and the full output with an extra `verbosity: 1` parameter so it requires `ansible-playbook`. What do you think about this? @richm what is your opinion?

I think showing `stderr_lines` by default, and requiring the user to specify extra verbosity, is a good idea.  If there is already a mechanism in the network role by which the user can request extra verbosity, then I think you should use it.
