### ISSUE TITLE
KeyError "type" in connection

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#40]
When a connection is to be removed ```connection['type']``` causes a KeyError when using the initscripts backend and no type is defined. This should fix it:

```
diff --git a/library/network_connections.py b/library/network_connections.py
index 271ab40..4922b13 100755
--- a/library/network_connections.py
+++ b/library/network_connections.py
@@ -2650,7 +2650,7 @@ class Cmd_initscripts(Cmd):
     def run_prepare(self):
         Cmd.run_prepare(self)
         for idx, connection in enumerate(self.connections):
-            if connection['type'] in [ 'macvlan' ]:
+            if connection.get('type') in [ 'macvlan' ]:
                 self.log_fatal(idx, 'unsupported type %s for initscripts provider' % (connection['type']))
 
     def check_name(self, idx, name = None):
```

The exception was: ```File "/tmp/ansible_jD4yqb/ansible_module_network_connections.py", line 2813, in <module>     cmd.run()   File
"/tmp/ansible_jD4yqb/ansible_module_network_connections.py", line 2398, in run     self.run_prepare()   File "/tmp/ansible_jD4yqb/ansible_module_network_connections.py", line 2654, in run_prepare     if
connection['type'] in [ 'macvlan' ]: KeyError: 'type'```

**Comment by thom311** [comment]
patch looks right to me.
