### ISSUE TITLE
Make it possible to run unit tests test_network_connections.py easily

### ISSUE THREAD

**Issue by thom311** [linux-system-roles/network#411]
Installing `tox` to run the unit tests is not straight forward.

The roles' README doesn't mention how to run unit tests.
Then you could read `https://github.com/linux-system-roles/tox-lsr/blob/main/README.md`, which is not a straight forward description of what to do either. At the very least should a CONTRIBUTING file explain how to do it in (at most) three commands.

Also, installing tox requires installing a lot of dependencies.

In the past, it was possible to call `pytest test_network_connections.py`, and it would just work.
It should just work, because test_network_connections.py tests the ArgValidator and has little extra dependencies (like on ansible modules). When developing something on the ArgValidator, it's important to be conveniently able to run the unit tests.

Pull request #404 attempted to do this, but the approach was not considered good. A better approach is necessary.

This is important, because running unit tests during development is important.

**Comment by thom311** [comment]
@cathay4t, it is IMO quite important, that a developer can run unit tests without major obstacles.

The solution at #404 may not be preferable (although, I personally don't don't dislike it).

If a different solution should be done, then please provide one. Otherwise, let's merge #404 -- at least as a temporary solution.

Alternatively, this was broken by commit 9c86ff6f767ee83e09dc9260c8f75b144c8ec1b4. @richm how do you think this should be fixed?

**Comment by richm** [comment]
> @cathay4t, it is IMO quite important, that a developer can run unit tests without major obstacles.
> 
> The solution at #404 may not be preferable (although, I personally don't don't dislike it).
> 
> If a different solution should be done, then please provide one. Otherwise, let's merge #404 -- at least as a temporary solution.
> 
> Alternatively, this was broken by commit [9c86ff6](https://github.com/linux-system-roles/network/commit/9c86ff6f767ee83e09dc9260c8f75b144c8ec1b4). @richm how do you think this should be fixed?

I don't know - but as long as whatever the proposed solution is that doesn't break tox or integration CI tests is ok.

**Comment by cathay4t** [comment]
I will work on this issue.

**Comment by thom311** [comment]
Seems the branch #435 was never finalized. The problem still exists.
The solution from https://github.com/linux-system-roles/network/pull/404 works, AFAIS.

Could we get a non-perfect solution (#404), if nobody is working on fixing this? Being able(*) to run unit tests is very important (to me).

(*) maybe you think running unit tests is easy and and already reasonable low effort. If I cannot simply type `pytest $FILE`, then IMO that is not good enough.

**Comment by tyll** [comment]
> Installing `tox` to run the unit tests is not straight forward.
> 
> The roles' README doesn't mention how to run unit tests. Then you could read `https://github.com/linux-system-roles/tox-lsr/blob/main/README.md`, which is not a straight forward description of what to do either. At the very least should a CONTRIBUTING file explain how to do it in (at most) three commands.

#479 explains this now with three steps (installing tox, installing tox_lsr and calling tox). Given that installing and running tox are common tasks for Python devs and only installing tox_lsr is a custom step for the network role, this seems to be easy enough.

> Also, installing tox requires installing a lot of dependencies.

Most depenencies come from the all the python versions that tox recommends which are also useful to actually run the tests against all python versions.
