### ISSUE TITLE
[feature] support BGP peering

### ISSUE THREAD

**Issue by anthr76** [linux-system-roles/network#424]
I'm interested in using this great feature packed role. Question, I'm wondering if BGP peering is within the scope of this role? If so is there interst in adding it?

**Comment by tyll** [comment]
Currently, it is not planned. Would you be able to contribute the changes with our guidance and review? What exactly do you need? What needs to be configured and how for this?

**Comment by liangwen12year** [comment]
we have not heard back from the reporter, thus, close this issue. But please reopen this issue if needed.
