### ISSUE TITLE
Will OpenVSwitch be supported?

### ISSUE THREAD

**Issue by b1r63r** [linux-system-roles/network#426]
I would really like to see OVS being supported through this role. Are there plans for this?
For NM there is NetworkManager-ovs, so that side should be rather easy to cover

**Comment by tyll** [comment]
Currently, this is not planned. Would you be able to contribute this with our guidance and review? Which features do you need?

**Comment by b1r63r** [comment]
I really like the way the network role gives me a robust way to reconfigure a server newly installed using only one network interface to a bond into a bridge and move the host over to a macvlan port. Without any problems when the existing network interface gets cut off and transferred to the macvlan bridge.
So I would like to do the same for ovs bridges. Be able to take a default fedora/centos/rhel install and use ansible to rewire to a ovs bridge with trunk port over a bond out to external switch and ovs connectivity for both the host itself and vm's/containers.
My personal preference is nm over old style config files (even if I have been working on unix systems since mid eighties) so I would be happy with something that uses NetworkManager-ovs.
This is currently for my personal little lab, but I would see this as a very useful extension of the role with ovs being a large part of okd/OpenShift and other modern platforms.

**Comment by tyll** [comment]
This is now supported using `network_state` with Nmstate.
