### ISSUE TITLE
Inconsistent naming makes it messy to use

### ISSUE THREAD

**Issue by okapia** [linux-system-roles/network#437]
At work where I deal with RHEL 8 systems, the roles are available in an RPM named `rhel-system-roles`. While working from home, I'm running Centos stream 9 in VMs and deploying playbooks with ansible from my own system which runs a different OS. For anything that isn't Fedora/RHEL/Centos, I'd have to pull the roles with ansible-galaxy and they seem to then be `fedora.linux_system_roles`. Or is it dashes instead of underscores? I'd prefer to just check in a `requirements.yml` or whatever file so that it is easy for anyone on the team with whatever setup to ensure they have copies of the roles installed.

I've spent far too long trawling through the documentation trying to work out what I could put in such a requirements file. I can't get anything much to work with `ansible-galaxy install role -r`. Also how might I specify the role in the playbook to be independent of the setup? ("fedora.linux_system_roles.network" works here but not on the RHEL systems.) Can this be specified in a way that is portable?

**Comment by tyll** [comment]
@richm do you have any suggestions?

**Comment by richm** [comment]
I would suggest using the collection format wherever possible: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html

If you are not using RHEL, this means you would use the collection from Galaxy - the `fedora.linux_system_roles` (with underscores - you cannot use names with dashes with collections - yes, this makes it inconsistent because the project is named `linux-system-roles` with dashes . . .)
You can install collections with a requirements file: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file
To use the network role from the collection:
```
- include_role:
    name: fedora.linux_system_roles.network
  vars:
    network_connections:
      ...
```
However, this poses a problem for reusing the same playbook with RHEL (and Centos Stream 9) if you want to use the RPM package rhel-system-roles, because the collection is renamed as `redhat.rhel_system_roles`.  We have not found an elegant solution to the problem where you want to use the same playbook with RHEL and without RHEL.

**Comment by tyll** [comment]
Can we ship symlink named fedora.linux_system_roles that points to redhat.rhel_system_roles on RHEL and maybe also symlinks for the roles that use underscores instead of dashes?

**Comment by richm** [comment]
> Can we ship symlink named fedora.linux_system_roles that points to redhat.rhel_system_roles on RHEL and maybe also symlinks for the roles that use underscores instead of dashes?

It won't be that simple - collections need metadata too - so there will have to be a galaxy.yml or a MANIFEST.json or the like in a directory called `/path/to/ansible_collections/fedora/linux_system_roles` with metadata that describes it as the `fedora.linux_system_roles` collection - possibly other metadata as well.  It isn't like the legacy role format where the role lookup/inclusion mechanism in Ansible only cares about the directory name, and not the contents.

**Comment by richm** [comment]
If you want to continue to use the legacy role format, we will continue to publish the legacy roles (for the foreseeable future, no guarantees about dates and availability in the future) to https://galaxy.ansible.com/linux-system-roles - as you can see, all of the roles have been updated pretty recently (but I'm not sure when the network team is planning to do another release - but 1.4.0 is not very old).  If you do use the legacy role format, then the RHEL/CentOS RPM package *does* provide the aforementioned symlinks, so you can use either `linux-system-roles.network` or `rhel-system-roles.network` (also note that with the legacy role format, you can use dashes, so no underscores there).

**Comment by tyll** [comment]
@okapia it seems there is nothing that we can do in this GitHub project directly, please feel free to file a BZ against Fedora, RHEL or CentOS Stream to track the packaging bits, there. This will allow you to get notifications if something changes.

I will close this issue now. If there is anything that you would like to add, feel free to open the issue if necessary, file a new one or reach out on the mailing list.

**Comment by okapia** [comment]
Thats fine to close it. Thanks for the thoughtful responses.

**Comment by richm** [comment]
@okapia have you tried to use the `collections` keyword? e.g.
```
- hosts: all
  collections:
    - fedora.linux_system_roles
  tasks:
    - include_role:
        name: network
      vars: ...
```
see https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#simplifying-module-names-with-the-collections-keyword for more info - I realize the docs are not clear, in that it makes it seem as though 1) the `collections` keyword must be used in the role metadata and 2) `collections` is only good for look ups of module and plugins, but it does work with roles as well.

**Comment by tyll** [comment]
@richm how is this example solving the problem? Is this supposed to work in both RHEL and Fedora? Since it uses the fedora prefix, it would not work on RHEL AFAIU (I did not test it).

**Comment by richm** [comment]
> @richm how is this example solving the problem? Is this supposed to work in both RHEL and Fedora? Since it uses the fedora prefix, it would not work on RHEL AFAIU (I did not test it).

AFAIK, you would still have to change your playbook - but the positive is that you only have to change the playbook in one place in order to reuse that playbook for both upstream and downstream.  The upstream playbook looks like this:
```yaml
- hosts: all
  collections:
    - fedora.linux_system_roles
  tasks:
    - include_role:
        name: network
      vars: ...
```
the downstream playbook looks like this:
```yaml
- hosts: all
  collections:
    - redhat.rhel_system_roles
  tasks:
    - include_role:
        name: network
      vars: ...
```
