### ISSUE TITLE
LACP (802.3ad) Support lacp_rate

### ISSUE THREAD

**Issue by QCU87Z** [linux-system-roles/network#439]
Hi,

I am trying to set up a bonded link with LACP using this role. The switch this server connects to is configured for LACP rate fast.

I cant see a way to configure "lacp_rate".

I would expect to see it under the bond options, a quick look through the code suggests it might not be exposed.

The bond is currently functioning but having it set to fast is how we would normally configure our servers and the failover time is quite a bit quicker.

Cheers

Ash

**Comment by liangwen12year** [comment]
This PR is addressing the lacp rate and other bonding options, https://github.com/linux-system-roles/network/pull/376, but the original author is not updating the PR anymore, which is the reason that the PR was closed. Are you interested in committing in that PR and being a co-owner for that PR ? If you wish, just reopen that PR.

**Comment by liangwen12year** [comment]
All the bonding options support have been implemented in this PR, https://github.com/linux-system-roles/network/pull/452, let us close this issue.
