### ISSUE TITLE
Not possible to create bond from InfiniBand interfaces

### ISSUE THREAD

**Issue by vpal** [linux-system-roles/network#475]
Greetings,

I'm using the fedora.linux_system_roles collection.
I wanted to create a bond from two InfiniBand interfaces with the network role.
I ran into the following error: ` msg: 'fatal error: configuration error: connections[1].controller: bond only supports infiniband ports in active-backup mode`

This is due to a typo in the code that checks the configuration, in this lline: https://github.com/linux-system-roles/network/blob/59be6188579cc61a30230f978f38f67878251abc/module_utils/network_lsr/argument_validator.py#L2082
There should be a dash (-) instead of an underscore (_).

Thanks

**Comment by cathay4t** [comment]
Nice catch! I will fix it in #476 . Thanks!

**Comment by vpal** [comment]
@cathay4t thanks a lot for the very quick fix.
Do you happen to know when this is going to be released to https://galaxy.ansible.com/fedora/linux_system_roles

**Comment by vpal** [comment]
@richm @cathay4t , thanks a lot, that is very much appreciated.

**Comment by liangwen12year** [comment]
Sure.

**Comment by liangwen12year** [comment]
> Sure.



> > > @vpal We intend to release every 6 months. But if you need it badly, we can do a quick small release. @richm Can we?
> > 
> > 
> > Sure. Can someone on your team make a Changelog and Release Notes? Then I can do the tagging and releasing.
> 
> @liangwen12year would you be able to do this?

Sure.

**Comment by richm** [comment]
role is updated https://galaxy.ansible.com/linux-system-roles/network
working on collection

**Comment by richm** [comment]
collection is updated https://galaxy.ansible.com/fedora/linux_system_roles - 1.18.0

**Comment by vpal** [comment]
> collection is updated https://galaxy.ansible.com/fedora/linux_system_roles - 1.18.0

That is truly awesome, thanks a lot to all of you.
