### ISSUE TITLE
Include vlan: id: 123 in README.md

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#491]
https://github.com/linux-system-roles/network/blob/main/README.md#type-vlan  needs to document how to specify the VLAN id (and other vlan settings if there are any).

**Comment by Precious000** [comment]
Hi
I’m an outreachy intern, I’ll like to work on this, kindly assign it to me. Thanks

**Comment by marituhone** [comment]
hello,
@tyll  can you assign this task for me

**Comment by richm** [comment]
> hello, @tyll , @ffmancera can you assign this task for me, i want to work on it

Sorry - looks like someone else has been assigned - would you like to be assigned to the other issue you requested instead? https://github.com/linux-system-roles/network/issues/285#issuecomment-1991000761

**Comment by liangwen12year** [comment]
The PR https://github.com/linux-system-roles/network/pull/685 was merged upstream.
