### ISSUE TITLE
Support changing the IPv6 Address generation mode

### ISSUE THREAD

**Issue by joneuhauser** [linux-system-roles/network#500]
On Ubuntu 20.04, nm-managed connections by default use ipv6.addr-gen-mode = "stable-privacy". When using SLAAC, for obtaining a static address, setting this to "eui64" is required. I haven't found a way to do this with the role provided here (thanks a lot, by the way!). My current workaround uses the nmcli module additionally, but of course this leads to problems with idempotence. It would be nice if system-roles.network provided a way to set this option.

The relevant settings in NM are:

https://lazka.github.io/pgi-docs/NM-1.0/constants.html#NM.SETTING_IP6_CONFIG_IP6_PRIVACY

https://lazka.github.io/pgi-docs/NM-1.0/enums.html#NM.SettingIP6ConfigAddrGenMode

**Comment by liangwen12year** [comment]
Thanks, this sounds to me like a new feature request, I will look into it.

**Comment by liangwen12year** [comment]
Did you try the `network_state` variable, https://github.com/linux-system-roles/network/#variables ? IPv6 Address generation mode is supported by the `network_state`.
