### ISSUE TITLE
Parser for routing table database is too strict

### ISSUE THREAD

**Issue by bsteinb** [linux-system-roles/network#507]
The parser for the `iproute2` routing table database (`/etc/iproute2/rt_tables` etc.) in `module_utils/network_lsr/argument_validator.py:IPRouteUtils` is too strict. It asserts that entries/lines in the file are of the form `254 main` where the numeric id and the name must be separated by a single space character only. However, the [original parser](https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/lib/rt_names.c#n38) uses something like

```c
sscanf(p, "%d %s\n", id, namebuf)
```

Note that [the semantics of `sscanf` etc.](https://en.cppreference.com/w/c/io/fscanf) are such that any single whitespace character in the format string consumes all available consecutive whitespace characters in the input (spaces, tabs, etc.). The [default `/etc/iproute2/rt_tables`](https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/etc/iproute2/rt_tables) indeed separates the two fields by tabs instead of spaces.

**Comment by bsteinb** [comment]
> That is known to be more strict, because iproute2's parsing seems too lax to me, accepting things that it shouldn't accept.

Is the file format documented outside of the implementation of the original parser in iproute2? I could not find anything. If it is not, how do you arrive at the conclusion that it is too lax?

> a more useful report would be to list the exact files that you have

I provided a link to the default configuration file that is included in the iproute2 package, above, but I can reproduce it here verbatim if that helps:

```
#
# reserved values
#
255	local
254	main
253	default
0	unspec
#
# local
#
#1	inr.ruhep
```

This file is used as `/etc/iproute2/rt_tables` as is on RHEL 8 and its derivatives (installed via the `iproute` RPM). The role fails to parse this, since the file uses tabs instead of spaces as the field separator. The original parser in the general case will allow a sequence of one or more white space characters (according to `isspace(3)`) as field separators whereas the role only allows a single space (`' '`).

**Comment by thom311** [comment]
you are completely right. Opened an MR. Thanks.

The issue was caused by not realizing that `scanf()` treats whitespace they way you say (which is of course sensible, on part of `scanf()`).

**Comment by bsteinb** [comment]
No problem. I had to look up `scanf` as well.

I left a review with some things I noticed on the MR, I hope that was not too forward of me.

**Comment by thom311** [comment]
that was very useful. So many plunders :) Thank you!
