### ISSUE TITLE
How to setup MAC address of bonded interface?

### ISSUE THREAD

**Issue by Hoeze** [linux-system-roles/network#517]
Hi, how would I setup a bonded interface with my own specified MAC address?

**Comment by Hoeze** [comment]
In other words, how to set `cloned-mac-address` for interfaces?

**Comment by liangwen12year** [comment]
Currently, `a 'mac' address is only allowed for type 'ethernet' or 'infiniband'` [1], but it can be a feature candidate for the next release.

[1]  https://github.com/linux-system-roles/network/blob/main/module_utils/network_lsr/argument_validator.py#L2041

**Comment by liangwen12year** [comment]
https://github.com/linux-system-roles/network/pull/525, this PR supports the `cloned-mac-address`.
