### ISSUE TITLE
Eliminate non-inclusive language

### ISSUE THREAD

**Issue by nhosoi** [linux-system-roles/network#546]
Hello, we have a project to eliminate non-inclusive language from the linux-system-roles.

Running a utility woke (now it's supported in tox. please install the latest tox-lsr and run tox -e woke), two non-inclusive words are reported - dummy, whitelist, blacklist, master, and slave.

Can we replace them with more appropriate words? We are worried some of the words are coming from the network subsystems themselves that the network role depends upon. I'd think "eliminating non-inclusive language" is a common project among us including the subsystems. How are they solving the issue? If the network subsystems are already working on them, we could follow their effort.

Can we ask you to share the network team's policy on this matter with us? Thanks!

**Comment by nhosoi** [comment]
[Output from `tox -e woke`](https://github.com/linux-system-roles/network/files/10280136/network-woke.txt)

**Comment by liangwen12year** [comment]
AFAIK, @ffmancera  is working on the conscious language in NM side. For the non-inclusive language relied on the NM side, I will coordinate with Fernando to properly address this.  Thanks for reporting the issue.

**Comment by richm** [comment]
Looks like many of these issues will be solved by adding `# wokeignore: rule=master` comments e.g. https://github.com/linux-system-roles/network/blob/main/module_utils/network_lsr/ethtool.py#L26

https://github.com/linux-system-roles/network/blob/main/.mdl_style.rb#L2

etc.

Use of the word "dummy" appears in many names of test devices, variables, and some files.  These will preferably be renamed.  However, it does appear to be used as an NM keyword, so we'll have to add a wokeignore comment for those uses.

**Comment by nhosoi** [comment]
@liangwen12year, @richm, could you please take a look at this PR?
https://github.com/linux-system-roles/network/pull/551
Not sure why this test failed, though...
coverage/coveralls — Coverage decreased (-1.0%) to 42.421%

**Comment by nhosoi** [comment]
https://github.com/linux-system-roles/network/pull/551 is merged.
Thank you for reviewing and merging the pr.
