### ISSUE TITLE
Test if persistence of profiles works as expected

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#55]

**Comment by a-mere-peasant** [comment]
is a test for all types of connections needed separately or  would it be fine to do it for just any one type ?

would a playbook to set persistent_state=present and state=up to set the profile and then checking active profiles with nmcli and then running a playbook to change persistent_state=absent and then checking active profiles be enough ?

**Comment by tyll** [comment]
This issue is too vague to be kept open. Not sure, what it was about, initially, to be honest.
