### ISSUE TITLE
Consider allowing to specify bond slaves as attribute of a bond master

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#57]
Instead of requiring bond slaves to be specified as individual profiles it might make sense to mention the members directly in the master configuration. This is also suggested here: https://bugzilla.redhat.com/show_bug.cgi?id=1508614#c4

**Comment by pcahyna** [comment]
If the slaves are nested under the master configuration, it seems to imply that their names must be only locally unique (inside the master connection). As it is not, as I understand, the case - connection names must be globally unique - I think the current situation where the slaves are on the same level makes more sense.
I.e. let's nest things only when the nesting corresponds to the scope/namespace of names.

**Comment by tyll** [comment]
Closing. This seems to be mostly a cosmetic issue that needs too much effort.
