### ISSUE TITLE
add 'auto-dns' option also to network_connections

### ISSUE THREAD

**Issue by sercanyaldiz** [linux-system-roles/network#599]
Hello,

I would like to use the same 'auto-dns' option to disable DHCP dns record for network_connections

The command that is being used with nmcli:
nmcli connection modify eth0 ipv4.ignore-auto-dns yes

**Comment by liangwen12year** [comment]
Yes, `auto-dns` is already supported in network_state. Just out of curiosity, why do you prefer the `network_connections` instead of the `network_state`?

**Comment by sercanyaldiz** [comment]
@liangwen12year  Hi i have one dns server that I use for my lab envirountment. When I don't set auto-ignore I will have a second NS from DHCP pushed. That's confusing.

I just want a single ip `192.168.2.13` in /etc/resolve.conf , because that is what I have defined. I can also add a dummy ip as a list to dns to fix it, but having the auto-dns option in network_connection would be better

vars:
    network_connections:
      - name: eth0
        persistent_state: present
        state: up
        type: ethernet
        interface_name: eth0
        autoconnect: yes
        ip:
          dhcp4: yes
          auto6: no
          dns: 192.168.2.13
          dns_search: home.lab.com
          ipv6_disabled: true
      - name: "Wired connection 1"
        persistent_state: absent

**Comment by liangwen12year** [comment]
Thanks for the explanation, I am already self-assigned the task and will support it in the near future.

**Comment by sercanyaldiz** [comment]
@liangwen12year thanks. Looking forward to see your implementation.

**Comment by liangwen12year** [comment]
Fixed by https://github.com/linux-system-roles/network/pull/611.

**Comment by sercanyaldiz** [comment]
Thank you @liangwen12year!
