### ISSUE TITLE
Verify and document no-aaaa DNS option

### ISSUE THREAD

**Issue by myllynen** [linux-system-roles/network#612]
Upstream (glibc) and recent distribution releases (such as RHEL 8.7/9.1) have added support for the `no-aaaa` DNS resolver option which prevents systems doing AAAA queries. This is very much wanted in IPv4-only environments.

It would be good to verify that `no-aaaa` can be used with this role and after would be nice to mention `no-aaaa` in the README list of the supported DNS options.

Thanks.

**Comment by liangwen12year** [comment]
Yes, this can be a good feature candidate for the `network_connections` variable, currently, DNS option is not supported by the `network_state` variable.  I will work on it soon.

**Comment by liangwen12year** [comment]
Fixed by https://github.com/linux-system-roles/network/pull/619.
