### ISSUE TITLE
Add support for veth pair

### ISSUE THREAD

**Issue by mnasiadka** [linux-system-roles/network#682]
Currently the only supported veth is macvlan - not real veth pair like here: https://developers.redhat.com/blog/2018/10/22/introduction-to-linux-interfaces-for-virtual-networking#veth

Unless I'm mistaken of course.

**Comment by liangwen12year** [comment]
Do you try out the `network_state`, the veth type is supported in  `network_state`, https://nmstate.io/examples.html#interfaces-veth.

**Comment by liangwen12year** [comment]
@mnasiadka ^^, in case that you did not see my comments.

**Comment by mnasiadka** [comment]
Thanks for tagging - missed that, will have a try tomorrow.

**Comment by liangwen12year** [comment]
Have not received any response from the reporter, thus, close this issue as stale.
