### ISSUE TITLE
[RFE] add profile setting ignore-error-if-absent to ignore errors when downing a profile that does not exist

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#70]
Currently the role fails when ask to set a profile to `down` when the profile is not completely defined in the profile and does not exist on the target system. One could argue that a profile is `down` when  it does not exist on the system. However, one could also argue that the role should report this as an error in case there is a typo. Introduce a setting called `ignore-error-if-absent` that when it is true ignores the error when a profile is undefined and should be set to `down`.

**Comment by pcahyna** [comment]
what does it mean "when the profile is not completely defined in the profile"? Can you provide an example of such a profile, as a snippet of the network_connections variable?
> when the profile is not completely defined in the profile and does not exist on the target system.

What will happen when the profile is not completely defined, but it DOES exist on the target system?

**Comment by tyll** [comment]
> what does it mean "when the profile is not completely defined in the profile"? Can you provide an example of such a profile, as a snippet of the network_connections variable?

It is basically this, just a name and the state:
https://github.com/linux-system-roles/network/blob/master/tests/down-profile.yml

> What will happen when the profile is not completely defined, but it DOES exist on the target system?

Then it will now down the profile using `ifdown $profile` or via Network Manager because all the required information is available.

When `interface_name` is defined, we can also call ` ip link set dev  $interface state down` when the profile is not found but the interface exists to allow to down interfaces for which the profile was already set to `absent`.

**Comment by pcahyna** [comment]
> Currently the role fails when ask to set a profile to `down` when the profile is not completely defined in the profile and does not exist on the target system. One could argue that a profile is `down` when it does not exist on the system. However, one could also argue that the role should report this as an error in case there is a typo.

What about reporting an error only if the profile does not exist AND the corresponding interface does not exist either? (By "corresponding interface" I mean the interface determined in the standard way - i.e. match on `interface_name` (with the default being `name`) or `mac`.)
If there is a corresponding interface, then presumably it was not a typo.

**Comment by pcahyna** [comment]
Thinking more about it, I don't think we should worry about typos. Not being able to detect typos in some cases is the price to pay for idempotency, which is one of the key concepts in Ansible. The file module does not report an error with state=absent either, even if the file is not there and the name given could be a typo. This is by design; contrast with the rm command, which can detect typos in this way, but is not idempotent.

**Comment by tyll** [comment]
> Thinking more about it, I don't think we should worry about typos. Not being able to detect typos in some cases is the price to pay for idempotency, which is one of the key concepts in Ansible. The file module does not report an error with state=absent either, even if the file is not there and the name given could be a typo. This is by design; contrast with the rm command, which can detect typos in this way, but is not idempotent.

Ok, let's close this and follow up in #188
