### ISSUE TITLE
[RFE] default to currently used network provider

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#71]
Instead of defaulting to a network provider depending on the platform check if the network service or NetworkManager are already enabled and use the respective service.

**Comment by pcahyna** [comment]
I believe the provisional decision was to detect the current provider (network service or NetworkManager), and if it is different than the default based on the platform check, fail, thus forcing the user to provide the value explicitly.

**Comment by pcahyna** [comment]
This module could be helpful.
https://docs.ansible.com/ansible/latest/modules/service_facts_module.html#service-facts-module

**Comment by tyll** [comment]
Auto-detection could be very complicated, when there are corner cases.
- should we check only whether the services are running or also whether they are enabled?
- what if one is enabled but the other is running?
- what if both are enabled? (and only one is running?)
- should we also stop/disable the other service when the user specifies a provider?

In general, since the default is also the only possibility on RHEL6, we only need to check for newer systems,whether there is an indication that a user wants to use initscripts instead of NetworkManager but I am not so sure what these criteria might be since they might just run both at the same time without too many problems so users might forget to disable the other service. It happened to me in a test VM, too.

**Comment by pcahyna** [comment]
I would let the autodetection fail in the corner cases like those:

- should we check only whether the services are running or also whether they are enabled?
- what if one is enabled but the other is running?
- what if both are enabled? (and only one is running?)

The following seems to be unrelated to autodetection:
- should we also stop/disable the other service when the user specifies a provider?

but it is an important question nevertheless. What does the role do now? Does it make sense to not stop/disable the other service when the user specifies a provider?

**Comment by tyll** [comment]
To identify the corner cases and fail, we would still need to check for all cases to identify that a corner case is present, so the complexity of checks is still present. For example a simple check for RHEL7 and newer would be to check whether initscripts is running and use it, if it is, without checking whether NetworkManager is also running or whether initscripts is actually enabled. But then the role would not fail in the corner cases.

Stoping/disabling the other service came up for me in this topic to make sure that after specifying a provider once, it would also be autodetected in the next run.

Currently the role only changes the current provider, e.g. installs, starts and enables it.

Also the more I think about it, IMHO failing when the autodetected value does not match the platform's default also reduces the usability of the role, since it would make it harder to specify generic playbooks that will just work for both providers.

**Comment by pcahyna** [comment]
>  Currently the role only changes the current provider, e.g. installs, starts and enables it.

Is it the right thing to do? The timesync role, when a provider is selected (no matter if given, detected or set by default) the conflicting service is disabled. As it does not make much sense to run both services simultaneously. I don't know whether it makes sense to not disable the other network service.

> Also the more I think about it, IMHO failing when the autodetected value does not match the platform's default also reduces the usability of the role, since it would make it harder to specify generic playbooks that will just work for both providers.

Question is, what should such generic playbooks do? Use the default provider for the given platform/release? Use the one currently running? Both have their pros and cons, so failing when the autodetected one is different from the platform default is the safest option.

A playbook can still be generic if you specify the provider in an inventory variable.
it can be also generic if it contains
```yaml
network_provider: "{{ network_provider_current }}"
```
for the autodetected one, or
```yaml
network_provider: "{{ network_provider_default }}"
```
for the platform default one.
This way, one can specify which of the choices should the generic playbook implement.

**Comment by tyll** [comment]
> Is it the right thing to do? The timesync role, when a provider is selected (no matter if given, detected or set by default) disables the conflicting service. As it does not make much sense to run both services simultaneously. I don't know whether it makes sense to not disable the other network service.

I just tested it on my local test VM. `systemctl stop network` killed the configuration for eth0 (NetworkManager was still running) and after I logged in via virt-manager, running `ifup eth0` activated the connection using NetworkManager. Seems to be the same as doing `nmcli con up "System eth0"`. So they are both connected somehow.

> Also, what does it mean "initscripts running"? There is no service running for initscripts, is there?

There is a service called `network` and with running I meant `systemctl is-active` returns `active`. This is the case when the network init script ran as far as I understand but there is no daemon running.

> Question is, what should such generic playbooks do? Use the default provider for the given platform/release? Use the one currently running? Both have their pros and cons, so failing when the autodetected one is different from the platform default is the safest option.

To change the state of a connection to `up`, `down` or `absent` (maybe `up` is problematic, though) it might not matter that much which backend is used. When there are changes to a connection, it might be a different problem.

> A playbook can still be generic if you specify the provider in an inventory variable.
it can be also generic if it contains
> `network_provider: "{{ network_provider_current }}"`

But then we would need to decide on a value for `network_provider_current` for the corner cases or fail the generic playbook. Currently my  test playbooks seem to work just fine for the test VM that has both services activated.

**Comment by tyll** [comment]
The new idea is to do the following:

- if the user specified a network_provider, use it
- check if Network Manager is running on RHEL7+, then use it and enable it
- if Network Manager is not running on RHEL7+, fail and ask the user to define initscripts as the network provider

This should provide consistency across a platform by default but does not change the network provider without explicit user approval.

**Comment by tyll** [comment]
This change will ask the user to specify nm as nework_provider in case they want to setup a CentOS 7 cloud image, since they seem to not use NetworkManager, see https://larsu.fedorapeople.org/logs/linux-system-roles-network-pull-74-82e4c1f-centos-7-20180721-083606/artifacts/ansible.log

https://linux-system-roles.github.io/ mentions CentOS to be supported.

**Comment by pcahyna** [comment]
This is a bit unfortunate and it might be better to just use the current provider in all cases. See hhttps://bugzilla.redhat.com/show_bug.cgi?id=1607638

**Comment by pcahyna** [comment]
> Just to be clear: we still consider to current provider as nm  when Network Manager is running (and ignore whether the network service  is running), correct? And just instead of failing as it happens  currently, we will just use the provider?

yes, I believe so.

> I am not 100% sure this is a good idea, since this will mean that the role will use different providers depending on which installation medium was used since I am pretty sure that when doing a regular installation of CentOS via the server image will install Network Manager. Not sure about a minimal install, though. But this will also mean we will loose consistency across the platform.

We had a similar conversation in the case of the timesync role. See https://bugzilla.redhat.com/show_bug.cgi?id=1597692. The difference with the network role is that the providers are not really conflicting. So, would it work to simply enable Network Manager always on RHEL 7/CentOS 7 unless the user explicitly sets provider: initscript? Is it safe? But I prefer the safer option of just continuing to use initscripts if Network Manager is not running. Yes, we lose consistency across the platform, but that's due to the images themselves being inconsistent and we just respect that. The users can obtain consistency if they want by setting
```yaml
network_provider: "{{ network_provider_default }}"
```

**Comment by tyll** [comment]
I was actually considering to remove the `network_provider_default` variable when implementing the auto-detection without failure since the default would be initscripts with switching to nm when it is running, therefore the notation of saying that nm is the default for RHEL7+ would not be true. Also when both are not running but for example systemd-networkd, the role would use initscripts.

Also I would not consider users using the CentOS cloud image seeing as a conscious decision towards initscripts since the user cannot choose between network manager or initscripts there.

Simply enabling network manager on RHEL7 when the user does not specify a provider is the current behavior. Given that we did not receive any bug reports about this, it might also a good choice.

As far as I understood, running network manager and initscripts together does not hurt in general. Just if there are any ifcfg files with `NM_CONTROLLED=no`, then it might cause problems with network manager, since it would change the profile or maybe even to manage the device. This is what I took from our meeting in Brno and what @thom311 said. I planned to play around with this to find out more about it... However, it also let me to think that maybe checking for `NM_CONTROLLED=no` in `/etc/sysconfig/network-scripts` might be a better method to check whether the user explicitly does not want to use network manager and only then use initscripts instead of network manager. I would assume that the relevant images for RHEL/CentOS do not set this variable by default. What do you think?

**Comment by pcahyna** [comment]
I would not remove `network_provider_default`. It still has a well defined meaning in the sense that there is a default for a given system (not just for system-roles, but in general). In RHEL 6 the default is not to use NM, in RHEL 7 I believe it is to use it. We should expose the default so it can be easily used by users who want to set all their machines with the same OS release to the same value without thinking too much what this value is, i.e. use our opinionated choice.
> However, it also let me to think that maybe checking for NM_CONTROLLED=no in /etc/sysconfig/network-scripts might be a better method to check whether the user explicitly does not want to use network manager and only then use initscripts instead of network manager.

I am not sure, I would say if one is not using Network Manager (not enabled and started), one probably does not want to use it regardless of what is in the ifcfg files.
It is also a rather complicated to use, the rule that "if Netrwork Manager is running, use it, otherwise don't" is very simple and easy to understand.

**Comment by pcahyna** [comment]
As @tabowling said in another thread, it would be worth preserving the `NM_CONTROLLED=no` flag in existing connections when modifying them.

**Comment by pcahyna** [comment]
This would make the provider effectively a per-connection setting though and this seems like a big change.

**Comment by tyll** [comment]
> I am not sure, I would say if one is not using Network Manager (not enabled and started), one probably does not want to use it regardless of what is in the ifcfg files.
It is also a rather complicated to use, the rule that "if Network Manager is running, use it, otherwise don't" is very simple and easy to understand.

Checking whether `NM_CONTROLLED=no` is present in any `/etc/sysconfig/ifcfg-*` file is also very simple and easy to understand. And it makes the user to actively express their preference. Using the CentOS guest image does not necessarily express that someone does not want to use NetworkManager. If it is a base image that usually contains NetworkManager and the user removed it, then the intent is more clear. However these users might also express their wish explicitly in the role, as well.

> This would make the provider effectively a per-connection setting though and this seems like a big change.

yes, this should be properly considered since it might also cause interesting corner cases when for example a bond master is defined in NM but a slave is already configured with initscripts. IMHO it would make more sense to require a single network provider and implement missing features in network manager in case a user still requires initscripts for a certain feature.

I added some changes to #74 to not fail but use Network Manager when it was detected and changed the tests to also run for the other network provider on RHEL7+, since we cannot assume that the other provider will be initscripts in all cases.

**Comment by tyll** [comment]
About the default variable, maybe it should be renamed to something like `network_provider_os_default` or similar to properly show that it is the default based on the OS because in practice `initscripts` is now the default from the algorithm's point of view.

**Comment by pcahyna** [comment]
>   Using the CentOS guest image does not necessarily express that someone does not want to use NetworkManager.

True. But still enabling NM in that situation is a change and might have unexpected consequences. I think the general philosophy embodied e.g. in https://github.com/linux-system-roles/timesync/pull/12 is not to do changes unless the user asked for them. (It is also hard to distinguish what is intended and what is not.)

> `network_provider_os_default`

I like this suggestion, being more explicit does not hurt.
