### ISSUE TITLE
VRF Support

### ISSUE THREAD

**Issue by eliaswimmer** [linux-system-roles/network#715]
Networkmanager supports VRF since Version 1.24

VRF allows running services on custom routing tables with attached interfaces.

Create a VRF named **vrf0** with table **101**
`nmcli connection add type vrf ifname vrf0 con-name vrf0 table 101 ipv4.method disabled ipv6.method disabled`

Attach an interface to the VRF
`nmcli connection add type ethernet con-name enp1s0 ifname enp1s0 controller vrf0 port-type vrf ipv4.method manual ipv4.address 192.0.2.1/24 ipv4.gateway 192.0.2.254`

**Comment by liangwen12year** [comment]
vft is already supported in `network_state` variable, can you try to configure the vrf interface via `network_state` variable ?

**Comment by eliaswimmer** [comment]
I will do so!
