### ISSUE TITLE
EL-7 tests fails because there is no EPEL-7

### ISSUE THREAD

**Issue by jharuda** [linux-system-roles/network#718]
EPEL-7 was moved from `https://dl.fedoraproject.org/pub/epel/`. It causes network tests on EL-7 images to fail.

Find solution how to install those packages.

[1] https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

**Comment by liangwen12year** [comment]
The linked PR is already merged, let us close this issue.
