### ISSUE TITLE
RFE: Improve teamd support

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/network#97]
It seems to be supported in the code but it is not documented.

**Comment by tyll** [comment]
@aneagoe thank you! I will keep you update when we make progress here. I will be at [DevConf.cz](https://devconf.info/cz), [CentOS Dojo Brussels](https://wiki.centos.org/Events/Dojo/Brussels2019) and [FOSDEM](https://fosdem.org/2019/), soon. In case you are there as well and would like to chat about the role, please let me know.

**Comment by tyll** [comment]
I created a branch to support setting the runner now with NM: https://github.com/tyll/network/tree/team_options

The option name is not stable, yet. We are considering to adjust the schema to match the bonding options.

**Comment by tyll** [comment]
@aneagoe all the items from the TODO list in th PR are still undone plus tests are missing:

- [ ] Use a default to tx_hash in the role (NM seems to default to "tx_hash\": [\"eth\", \"ipv4\", \"ipv6\"]}}
- [ ] Add support for initscripts (this seems to require writing JSON in
the TEAM_CONFIG variable with shell quoting), example:
TEAM_CONFIG="{\"runner\": {\"name\": \"lacp\", \"tx_hash\": [\"eth\", \"ipv4\", \"ipv6\"]}}"
- [ ] Add more options
- [ ] Add documentation/example
- [ ] Add integration tests

Also we need a decision whether or not to abstract teamd/bonding settings in a more generic way. @pcahyna suggested it, I am currently not convinced that it is necessary. Also, at this point, this is not a priority, therefore someone who would like to do the coding would be good, too.

**Comment by aneagoe** [comment]
@tyll Understood. With regards to MODE vs RUNNER I'd keep things separate; there is a certain divergence between bond and team (ie outside of "broadcast" there's no overlap). It could be confusing to use a generic definition.
As well, how much should be validated with regards to TEAM_CONFIG? JSON validation can be easy to do, but for example checking if certain parameters are withing accepted ranges could become complex.
Would the branch you created already work in its simplest form (ie just choosing runner)?

**Comment by tyll** [comment]
Changing the runner should work when using NetworkManager but the branch does not match the requirements to be merged.
I would be fine with only doing JSON validation in the beginning and other validation on a best-effort base or not at all. @cathay4t what do you think?

**Comment by cathay4t** [comment]
If you guys are talking about the open the door of allowing user passing any json `TEAM_CONFIG` to teamd via `NM.SettingTeam.props.config`, I disagree. The teamd might changed their json config which require our
user to sync with it which is against our abstraction goal.

A better approach would be exposing all options provided by NM or only add requested options.

**Comment by aneagoe** [comment]
I'd be happy to see something either way. Right now we've decided internally to revert to bonding because it simply has better support in the role as opposed to teamd.

**Comment by cathay4t** [comment]
I will try to evaluating whether we can use the same schema for both bond and team where user can simply move from one to another simply.

**Comment by tyll** [comment]
Team support is not a priority for us and we don't have the capacity to move this further. My recommendations is to use bonding, instead. If there are features missing in bonding, please report them.
